version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fc:22:72:d5:81:47:97:45:5a:41:f8:6f:d5:08:9a:e2"
      - checkout      
      - run: 
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
